name: Node ESLint mdx environment

on:
  - push
  - pull_request


jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.8.1]

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install
        run:
          npm i
      - name: eslint install
        run:
          npm install eslint --save-dev

      - name: check eslint
        uses: actions/setup-node@v1
        working-directory: ./application
        run: eslint 'pages/**/*.mdx'
        