name: Proff HTML
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [19.8.1]
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

     - name: Set tocken
       env:
       gitToken: "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"
     - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run:
          npm i
      - name: npm run build
        run:
          npm run build
          
     
      - uses: anishathalye/proof-html@v2
        with:
          directory: ./.next
          enforce_https: false
          tokens: |
            {"https://github.com": "${{ env.gitToken }}"}
          ignore_url: |
            http://www.example.com/
            https://en.wikipedia.org/wiki/Main_Page
          ignore_url_re: |
            ^https://twitter.com/
          swap_urls: |
            {"^https://www.anishathalye.com/": "/"}